### ISSUE TITLE
helpers, custom hooks 테스트 코드 작성

### ISSUE THREAD

**Issue by edit8080** [linewalks/CLUE-ClientCore#29]
### 구현 및 개선하려는 문제에 대한 간결한 설명
- CLUE-ClientCore 내부 테스트 커버리지가 매우 낮은 문제를 확인
- 현재 테스트 커버리지 (statement : 21.11%, branch : 13.45%)

### 구현 및 개선을 위해 고려한 대안 설명
- 컴포넌트 안정화 작업이 남아있어 컴포넌트에 대한 테스트 코드 작성은 추후에 진행
- helpers, custom hooks 에 대한 로직을 위주로 테스트 코드 작성

### 구현 및 개선을 위한 추가 정보
- 없음

**Comment by edit8080** [comment]
헬퍼함수와 커스텀 훅에 대한 테스트 로직을 추가하였습니다.

- 전체 테스트 커버리지 (statement : 53.46%, branch : 38.51%)
- helpers 커버리지 (statement : 99.33%, branch : 94.96%)
- hooks 커버리지 (statement : 97.72%, branch : 94.44%)

![image](https://user-images.githubusercontent.com/30149272/147627724-31e2a75f-8370-4b13-959c-ec9a8fe2cdfb.png)

**Comment by liza0525** [comment]
test
